// @generated by `ruskel-snapshot`; do not edit.

pub mod musq_macros {
    //! Procedural macros for the musq crate.

    /// Derive combined encode and decode implementations.
    #[proc_macro_derive(Codec, attributes(musq))]
    pub fn Codec(input: proc_macro::TokenStream) -> proc_macro::TokenStream {}
    /// Derive a `Decode` implementation.
    #[proc_macro_derive(Decode, attributes(musq))]
    pub fn Decode(input: proc_macro::TokenStream) -> proc_macro::TokenStream {}
    /// Derive an `Encode` implementation.
    #[proc_macro_derive(Encode, attributes(musq))]
    pub fn Encode(input: proc_macro::TokenStream) -> proc_macro::TokenStream {}
    /// Derive a `FromRow` implementation.
    #[proc_macro_derive(FromRow, attributes(musq))]
    pub fn FromRow(input: proc_macro::TokenStream) -> proc_macro::TokenStream {}
    /// Derive JSON encode/decode implementations.
    ///
    /// The expanded code needs the musq `json` feature.
    #[proc_macro_derive(Json, attributes(musq))]
    pub fn Json(input: proc_macro::TokenStream) -> proc_macro::TokenStream {}
    /// Expand a SQL query from a format string and arguments.
    #[proc_macro]
    pub fn sql(input: proc_macro::TokenStream) -> proc_macro::TokenStream {}
    /// Expand a SQL query that maps rows into a destination type.
    #[proc_macro]
    pub fn sql_as(input: proc_macro::TokenStream) -> proc_macro::TokenStream {}
}
